module.exports = {
  check_run: "check_run",
  check_suite: "check_suite",
  commit_comment: "commit_comment",
  content_reference: "content_reference",
  create: "create",
  delete: "delete",
  deploy_key: "deploy_key",
  deployment: "deployment",
  deployment_status: "deployment_status",
  fork: "fork",
  github_app_authorization: "github_app_authorization",
  gollum: "gollum",
  installation:"installation",
  installation_repositories:"installation_repositories",
  issue_comment:"issue_comment",
  issues: "issues",
  label:"label",
  marketplace_purchase:"marketplace_purchase",
  member:"member",
  meta:"meta",
  milestone:"milestone",
  organization:"organization",
  org_block:"org_block",
  package:"package",
  page_build:"page_build",
  ping:"ping",
  project_card:"project_card",
  project_column:"project_column",
  project:"project",
  public:"public",
  pull_request: "pull_request",
  commit_comment: "commit_comment",
};
